using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Project_Leap_V3.frames
{
    /// <summary>
    /// This frame displays the total amount of money generated by the system
    /// </summary>
    public partial class AmountSystemGenerated : System.Web.UI.Page
    {
        /// <summary>
        /// This method calculates and displays the total amount of money generated by the system
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        protected void Page_Load(object sender, EventArgs e)
        {
            if ((int)HttpContext.Current.Session["User_lvl"] == 6)
            {
                ServiceReference1.Service1Client serv = new ServiceReference1.Service1Client();
                double amount = (double)serv.getAmountSystemGenerated();
                lblAmountR.Text = "R" + amount;
            }
        }
    }
}